"""Primeira migração: criando tabelas

Revision ID: 08c4b879e5a8
Revises: 
Create Date: 2026-03-28 17:25:53.537266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08c4b879e5a8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paciente',
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('data_nasc', sa.Date(), nullable=True),
    sa.Column('telefone', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('cpf')
    )
    op.create_table('atendimento',
    sa.Column('id_atendimento', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('cpf_paciente', sa.String(length=11), nullable=False),
    sa.Column('data_abertura', sa.Date(), nullable=True),
    sa.Column('hora_abertura', sa.Time(), nullable=True),
    sa.Column('tipo', sa.String(length=1), nullable=True),
    sa.Column('crm_medico', sa.String(length=15), nullable=True),
    sa.Column('especialidade', sa.String(length=40), nullable=True),
    sa.Column('convenio', sa.String(length=30), nullable=True),
    sa.Column('carteirinha', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('observacao', sa.String(length=100), nullable=True),
    sa.Column('data_encerramento', sa.Date(), nullable=True),
    sa.Column('hora_encerramento', sa.Time(), nullable=True),
    sa.Column('cid_principal', sa.String(length=10), nullable=True),
    sa.Column('procedimento', sa.String(length=20), nullable=True),
    sa.Column('qtd_medicamentos', sa.Integer(), nullable=True),
    sa.Column('valor_procedimentos', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['cpf_paciente'], ['paciente.cpf'], ),
    sa.PrimaryKeyConstraint('id_atendimento')
    )
    op.create_table('status_financeiro',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('cpf_paciente', sa.String(length=11), nullable=False),
    sa.Column('status_financeiro', sa.String(length=10), nullable=True),
    sa.Column('qtd_pendencias', sa.Integer(), nullable=True),
    sa.Column('valor_total_pendente', sa.Numeric(precision=11, scale=2), nullable=True),
    sa.Column('data_vencimento_mais_antiga', sa.Date(), nullable=True),
    sa.Column('permite_atendimento', sa.String(length=1), nullable=True),
    sa.Column('observacao', sa.String(length=100), nullable=True),
    sa.Column('data_geracao', sa.Date(), nullable=True),
    sa.Column('hora_geracao', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['cpf_paciente'], ['paciente.cpf'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prescricao',
    sa.Column('id_prescricao', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_atendimento', sa.BigInteger(), nullable=False),
    sa.Column('cpf_paciente', sa.String(length=11), nullable=False),
    sa.Column('data_prescricao', sa.Date(), nullable=True),
    sa.Column('hora_prescricao', sa.Time(), nullable=True),
    sa.Column('crm_medico', sa.String(length=15), nullable=True),
    sa.Column('codigo_medicamento', sa.BigInteger(), nullable=True),
    sa.Column('quantidade', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('unidade_medida', sa.String(length=4), nullable=True),
    sa.Column('observacao', sa.String(length=100), nullable=True),
    sa.Column('status_estoque', sa.String(length=12), nullable=True),
    sa.ForeignKeyConstraint(['cpf_paciente'], ['paciente.cpf'], ),
    sa.ForeignKeyConstraint(['id_atendimento'], ['atendimento.id_atendimento'], ),
    sa.PrimaryKeyConstraint('id_prescricao')
    )
    op.create_table('retorno_estoque',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_prescricao', sa.BigInteger(), nullable=False),
    sa.Column('codigo_medicamento', sa.BigInteger(), nullable=True),
    sa.Column('disponivel', sa.Numeric(precision=1), nullable=True),
    sa.Column('observacao', sa.String(length=100), nullable=True),
    sa.Column('data_importacao', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_prescricao'], ['prescricao.id_prescricao'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('retorno_estoque')
    op.drop_table('prescricao')
    op.drop_table('status_financeiro')
    op.drop_table('atendimento')
    op.drop_table('paciente')
    # ### end Alembic commands ###
